spring:
  datasource:
    name: mydb
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/1809b
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapperLocations: classpath*:mybatis/mapper-*.xml
  typeAliasesPackage: com.jk.bean

redis:
  database: 0
  host: 127.0.0.1
  port: 6379
  password:
  timeout: 5000
data:
  mongodb:
    uri: mongodb://127.0.0.1:27017/qsy

thymeleaf: content-type=text/html